version: '3'

services:
  redmine:
    image: redmine:4.0.0
    restart: always
    ports:
      - '8080:3000'
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/vendor/plugins:/usr/src/redmine/vendor/plugins
      - ./redmine/public/themes:/usr/src/redmine/public/themes
    environment:
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: example
      REDMINE_DB_DATABASE: 'redmine'
    
  db:
    image: postgres:11.1
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: example
      POSTGRES_DB: 'redmine'
    